name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: yarn install

      - name: type check
        run: yarn typecheck

      - name: lint check
        run: yarn lint

      - name: test check
        run: yarn test

      - name: build
        run: yarn build
